package ru.chavkin.em.linkshortener.service;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.exception.ConstraintViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.chavkin.em.linkshortener.entity.Link;
import ru.chavkin.em.linkshortener.entity.dto.ShortenRequest;
import ru.chavkin.em.linkshortener.entity.dto.ShortenResponse;
import ru.chavkin.em.linkshortener.entity.enumerated.ExceptionMessage;
import ru.chavkin.em.linkshortener.entity.mapper.LinkMapper;
import ru.chavkin.em.linkshortener.exception.LinkConstraintException;
import ru.chavkin.em.linkshortener.exception.LinkExpirationDateValueException;
import ru.chavkin.em.linkshortener.exception.LinkNotFoundException;
import ru.chavkin.em.linkshortener.exception.ShortCodeGenerationMaxAttemptsException;
import ru.chavkin.em.linkshortener.repository.LinkRepository;
import ru.chavkin.em.linkshortener.validator.LinkValidator;

import java.security.SecureRandom;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.IntStream;

import static ru.chavkin.em.linkshortener.entity.enumerated.Constants.*;

@Slf4j
@Service
@RequiredArgsConstructor
public class LinkService {

    private final LinkMapper linkMapper;
    private final LinkValidator linkValidator;
    private final LinkRepository linkRepository;

    /**
     * Method to create Link entity.
     * Accepts three parameters as input. In the absence of the passed alias,
     * it substitutes the shortCode in its place.
     * The shortCode is generated by the {@code generateShortCode()} method.
     *
     * @param request - ShortenRequest dto.
     * @return created {@link Link} entity.
     */
    @Transactional
    public ShortenResponse createShortLink(ShortenRequest request) {
        log.info("Link creating started.");
        linkValidator.validateUrl(request.originalUrl());

        String shortCode = generateShortCode();
        log.info("shortCode successfully generated: {}", shortCode);

        if (request.alias() == null || request.alias().isEmpty()) {
            log.debug("Alias is null or empty. Its value will be replaced by a shortCode.");

            Link link = save(request.originalUrl(), shortCode, shortCode, linkValidator.resolveTtlDays(request.ttlDays()));
            log.info("Link without the specified alias was saved successfully: {}", link);
            return linkMapper.fromEntityToResponse(link);
        }

        Link link = save(request.originalUrl(), shortCode, request.alias(), linkValidator.resolveTtlDays(request.ttlDays()));
        log.info("Link with the specified alias was saved successfully: {}", link);
        return linkMapper.fromEntityToResponse(link);
    }

    /**
     * Method to save Link entity.
     *
     * @param originalUrl - original url.
     * @param shortCode   - short code.
     * @param alias       - alias.
     * @param ttlDays     - time to live.
     * @return saved Link entity.
     */
    public Link save(String originalUrl, String shortCode, String alias, Integer ttlDays) {
        try {
            Link link = Link.builder()
                    .originalUrl(originalUrl)
                    .shortCode(shortCode)
                    .alias(alias)
                    .createdAt(OffsetDateTime.now())
                    .expiresAt(OffsetDateTime.now().plusDays(ttlDays))
                    .build();

            return linkRepository.save(link);
        } catch (ConstraintViolationException e) {
            throw new LinkConstraintException(
                    ExceptionMessage.LINK_WITH_CONSTRAINT_FIELD_ALREADY_EXISTS.getErrorMessage(),
                    ExceptionMessage.LINK_WITH_CONSTRAINT_FIELD_ALREADY_EXISTS.getErrorCode()
            );
        }
    }

    /**
     * Finds the link by alias or shortCode.
     * <p>
     * Search order:
     * 1. By alias
     * 2. By shortCode (if alias is not found)
     * <p>
     * Returns {@link Optional#empty()} if:
     * - link not found
     * - or the link has expired
     *
     * @param code shortCode or alias
     * @return Original url
     */
    public String getUrlByAliasOrShortCode(String code) {
        log.debug("Searching for link by code: {}", code);
        String trimmedCode = code.trim();
        if (trimmedCode.isEmpty()) {
            throw new IllegalArgumentException("code is empty");
        }
        Link link = linkRepository.findByAliasOrShortCode(trimmedCode)
                .orElseThrow(() -> new LinkNotFoundException(
                        ExceptionMessage.LINK_NOT_FOUND.getErrorMessage(),
                        ExceptionMessage.LINK_NOT_FOUND.getErrorCode()
                ));
        if (!isLinkActive(link)) {
            throw new LinkExpirationDateValueException(
                    ExceptionMessage.LINK_EXPIRED.getErrorMessage(),
                    ExceptionMessage.LINK_EXPIRED.getErrorCode()
            );
        }
        return link.getOriginalUrl();
    }


    /**
     * Checks if the link is active (not expired).
     */
    public boolean isLinkActive(Link link) {
        OffsetDateTime expiresAt = link.getExpiresAt();
        boolean isActive = expiresAt == null || expiresAt.isAfter(OffsetDateTime.now());
        if (!isActive) {
            log.debug("Link is expired: shortCode={}, alias={}, expiresAt={}",
                    link.getShortCode(), link.getAlias(), expiresAt);
        }
        return isActive;
    }

    /**
     * Method for checking for the exists shortCode in the repository
     * with a certain number of attempts.
     *
     * @return Checked for missing in the database, ready to use {@code shortCode}
     */
    public String generateShortCode() {
        return IntStream.range(0, SHORT_CODE_MAX_GENERATION_ATTEMPTS)
                .mapToObj(i -> generateRandomCode())
                .filter(code -> !linkRepository.existsByShortCode(code))
                .findFirst()
                .orElseThrow(() -> new ShortCodeGenerationMaxAttemptsException(
                        ExceptionMessage.SHORT_CODE_GENERATION_MAX_ATTEMPTS.getErrorMessage(),
                        ExceptionMessage.SHORT_CODE_GENERATION_MAX_ATTEMPTS.getErrorCode()
                ));
    }

    /**
     * Method for generating a string for a shortCode.
     * <p>
     * Uses the Stream Api in conjunction with {@code java.util.Random}.
     *
     * @return Generates a shortCode with a length of {@code SHORT_CODE_LENGTH} (6 characters),
     * using {@code SHORT_CODE_ALLOWED_CHARACTERS} (allowed characters).
     */
    public String generateRandomCode() {
        SecureRandom random = new SecureRandom();
        StringBuilder sb = new StringBuilder(SHORT_CODE_LENGTH);
        for (int i = 0; i < SHORT_CODE_LENGTH; i++) {
            int index = random.nextInt(SHORT_CODE_ALLOWED_CHARACTERS_LENGTH);
            sb.append(SHORT_CODE_ALLOWED_CHARACTERS.charAt(index));
        }
        return sb.toString();
    }

}
